version: "3.4"
services:
  postgres:
    container_name: socialmedia-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: socialmedia
      POSTGRES_PASSWORD: socialmedia

volumes:
  postgres_data: